/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sms_system.ui;

import com.mycompany.sms_system.businesslogic.UserLogic;
import com.mycompany.sms_system.entity.UserBean;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;


import javax.swing.ImageIcon;

/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        SetIconImage();

        ImageIcon myImage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icon/login_bg01.png")));
        Image img1 = myImage.getImage();
        Image img2 = img1.getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        jLabel2.setIcon(i);

//                ImageIcon myImage2 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icon_2/logolatest.jpg")));
//        Image img01 = myImage2.getImage();
//        Image img02 = img01.getScaledInstance(lblLogo.getWidth(),lblLogo.getHeight(),Image.SCALE_SMOOTH);
//        ImageIcon q = new ImageIcon(img02);
//        lblLogo.setIcon(q);
        ImageIcon myImage3 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icon_2/account.png")));
        Image img001 = myImage3.getImage();
        Image img002 = img001.getScaledInstance(lblIconUser.getWidth(), lblIconUser.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon h = new ImageIcon(img002);
        lblIconUser.setIcon(h);

        ImageIcon myImage4 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icon_2/lock (2).png")));
        Image img0001 = myImage4.getImage();
        Image img0002 = img0001.getScaledInstance(lblIconPassword.getWidth(), lblIconPassword.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon r = new ImageIcon(img0002);
        lblIconPassword.setIcon(r);

        ImageIcon myImage5 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icon_2/hide.png")));
        Image img00001 = myImage5.getImage();
        Image img00002 = img00001.getScaledInstance(lblShowPass.getWidth(), lblShowPass.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon z = new ImageIcon(img00002);
        lblShowPass.setIcon(z);

        ImageIcon myImage6 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icon_2/eye.png")));
        Image img000001 = myImage6.getImage();
        Image img000002 = img000001.getScaledInstance(lblHidePass.getWidth(), lblHidePass.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon l = new ImageIcon(img000002);
        lblHidePass.setIcon(l);
        lblHidePass.setVisible(false);
        lblShowPass.setVisible(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblHidePass = new javax.swing.JLabel();
        lblShowPass = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnExit = new javax.swing.JButton();
        lblErroruser = new javax.swing.JLabel();
        lblErrorpass = new javax.swing.JLabel();
        lblIconUser = new javax.swing.JLabel();
        lblIconPassword = new javax.swing.JLabel();
        btnLogin1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 204, 255, 70));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), null, null));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 335));

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setText("User Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 15, 96, 28));

        txtUserName.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(51, 51, 51));
        txtUserName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 15, 178, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel4.setText("Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 74, 96, 28));

        lblHidePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_2/eye.png"))); // NOI18N
        lblHidePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblHidePassMouseReleased(evt);
            }
        });
        jPanel2.add(lblHidePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 20, 20));

        lblShowPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_2/hide.png"))); // NOI18N
        lblShowPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblShowPassMousePressed(evt);
            }
        });
        jPanel2.add(lblShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 20, 20));

        txtPassword.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(51, 51, 51));
        txtPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 74, 178, -1));

        btnExit.setBackground(new java.awt.Color(0, 0, 153));
        btnExit.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(204, 204, 204));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        btnExit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnExitKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnExitKeyReleased(evt);
            }
        });
        jPanel2.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 100, 40));

        lblErroruser.setForeground(new java.awt.Color(255, 51, 51));
        lblErroruser.setPreferredSize(new java.awt.Dimension(0, 13));
        jPanel2.add(lblErroruser, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 43, 163, -1));

        lblErrorpass.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorpass.setPreferredSize(new java.awt.Dimension(0, 13));
        jPanel2.add(lblErrorpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 102, 163, -1));

        lblIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_2/account.png"))); // NOI18N
        jPanel2.add(lblIconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 18, 25, 25));

        lblIconPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_2/lock (2).png"))); // NOI18N
        jPanel2.add(lblIconPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 74, 25, 25));

        btnLogin1.setBackground(new java.awt.Color(0, 0, 153));
        btnLogin1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        btnLogin1.setForeground(new java.awt.Color(204, 204, 204));
        btnLogin1.setText("Login");
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });
        btnLogin1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLogin1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnLogin1KeyReleased(evt);
            }
        });
        jPanel2.add(btnLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 120, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 520, 300));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/login_bg01.png"))); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void lblShowPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowPassMousePressed
        lblHidePass.setVisible(true);
        lblShowPass.setVisible(false);
        txtPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_lblShowPassMousePressed

    private void lblHidePassMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHidePassMouseReleased
        lblHidePass.setVisible(false);
        lblShowPass.setVisible(true);
        txtPassword.setEchoChar('*');
    }//GEN-LAST:event_lblHidePassMouseReleased

    private void btnExitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnExitKeyPressed

    }//GEN-LAST:event_btnExitKeyPressed

    private void btnExitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnExitKeyReleased


    }//GEN-LAST:event_btnExitKeyReleased

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed

        if (txtUserName.getText().equals("") && (txtPassword.getText().equals(""))) {
            String out1 = "  fill out username";
            lblErroruser.setText(out1);
            String out2 = "  fill out password";
            lblErrorpass.setText(out2);

        } else if (txtPassword.getText().equals("")) {
            String out2 = "  please enter password";
            lblErrorpass.setText(out2);

            lblErroruser.setText(null);
        } else if (txtUserName.getText().equals("")) {
            String out1 = "  please enter username";
            lblErroruser.setText(out1);

            lblErrorpass.setText(null);

        } else {
            String username = txtUserName.getText();
            String Password = txtPassword.getText();

            UserBean usb = new UserBean();
            usb.setLogin_name(username);
            usb.setLogin_pass(Password);

            boolean Login = new UserLogic().Login(usb);

            if (Login) {
                JOptionPane.showMessageDialog(null, "Logging Successful");
                Dashboard dboard = new Dashboard();   // show the dashboard
                dboard.show();
                dispose(); // close the current form(login)
            } else {
                String out1 = "  invalid username";
                String out2 = "  invalid password";
                lblErroruser.setText(out1);

                lblErrorpass.setText(out2);
                txtPassword.setText(null);
                txtUserName.setText(null);
            }
        }
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void btnLogin1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLogin1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtUserName.getText().equals("") && (txtPassword.getText().equals(""))) {
                String out1 = "  fill out username";
                lblErroruser.setText(out1);
                String out2 = "  fill out password";
                lblErrorpass.setText(out2);

            } else if (txtPassword.getText().equals("")) {
                String out2 = "  please enter password";
                lblErrorpass.setText(out2);

                lblErroruser.setText(null);
            } else if (txtUserName.getText().equals("")) {
                lblErroruser.setText("  please enter username");

                lblErrorpass.setText(null);

            } else if (txtUserName.getText().equals("Admin") && (txtPassword.getText().contains("Admin123"))) //check user name & password
            {
                JOptionPane.showMessageDialog(null, "Logging Successful");
                Dashboard dboard = new Dashboard();   // show the dashboard
                dboard.show();
                dispose(); // close the current form(login)
            } else {

                String out1 = "  invalid username";
                String out2 = "  invalid password";
                lblErroruser.setText(out1);

                lblErrorpass.setText(out2);
                txtPassword.setText(null);
                txtUserName.setText(null);
            }
        } else {

        }
    }//GEN-LAST:event_btnLogin1KeyPressed

    private void btnLogin1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLogin1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogin1KeyReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Login().setVisible(true);
//            }
//        });
//        
//        
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblErrorpass;
    private javax.swing.JLabel lblErroruser;
    private javax.swing.JLabel lblHidePass;
    private javax.swing.JLabel lblIconPassword;
    private javax.swing.JLabel lblIconUser;
    private javax.swing.JLabel lblShowPass;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private  void SetIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icon_4/SystemIcon_02.png")));
    }


}
